{% set version = "1.6.0" %}

package:
  name: landlab
  version: {{ version }}

source:
  url: https://github.com/landlab/landlab/archive/v{{ version }}.tar.gz
  sha256: 2b1e2b0bf99322a26a893a3749b9d165f18040447118526e6b5e74e01e699277

build:
  number: 1000
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler("c") }}
  host:
    - python
    - pip
    - cython
    - numpy 1.11.*
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - xarray
    - matplotlib
    - netcdf4
    - six
    - pyyaml
    - statsmodels

test:
  requires:
    - pytest <3.7.2
  imports:
    - landlab
  commands:
    - export MPLBACKEND=Agg  # [not win]
    - pytest --pyargs landlab --doctest-modules -o doctest_optionflags="NORMALIZE_WHITESPACE IGNORE_EXCEPTION_DETAIL ALLOW_UNICODE"

about:
  home: http://landlab.github.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A python toolkit for modeling earth surface processes
  description: |
    Landlab creates an environment in which scientists can build
    a numerical landscape model without having to code all of the
    individual components. Landscape models compute flows of mass,
    such as water, sediment, glacial ice, volcanic material, or
    landslide debris, across a gridded terrain surface. Landscape
    models have a number of commonalities, such as operating on a
    grid of points and routing material across the grid. Scientists
    who want to use a landscape model often build their own unique
    model from the ground up, re-coding the basic building blocks
    of their landscape model rather than taking advantage of codes
    that have already been written.
  doc_url: https://landlab.readthedocs.io
  dev_url: https://github.com/landlab/landlab

extra:
  recipe-maintainers:
    - mcflugen
    - lsetiawan
    - ocefpaf
    - kbarnhart
