{% set version = "2.5.0" %}

package:
  name: landlab
  version: {{ version }}

source:
  url: https://github.com/landlab/landlab/archive/v{{ version }}.tar.gz
  sha256: 9dade74cccb1670ba6e9d6d9f4878d3bacef7991a626e4f3f2fa3a5fcbc01042
  patches:
    - exclude-tests-folder.patch  # prevent tests folder from being installed

build:
  number: 2
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py2k]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler("c") }}
  host:
    - python
    - pip
    - cython
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - bmipy
    - matplotlib-base
    - netcdf4
    - pyshp
    - pyyaml
    - richdem >=2.3
    - setuptools
    - scipy
    - statsmodels
    - xarray

test:
  requires:
  - pip
  #   - pytest
  #   - pytest-datadir
  imports:
    - landlab
  commands:
    - pip check
    - export MPLBACKEND=Agg  # [not win]
    # skipping the tests b/c they have some flaky repr comparisons
    # - pytest --pyargs landlab --doctest-modules -o doctest_optionflags="NORMALIZE_WHITESPACE IGNORE_EXCEPTION_DETAIL ALLOW_UNICODE"

about:
  home: http://landlab.github.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A python toolkit for modeling earth surface processes
  description: |
    Landlab creates an environment in which scientists can build
    a numerical landscape model without having to code all of the
    individual components. Landscape models compute flows of mass,
    such as water, sediment, glacial ice, volcanic material, or
    landslide debris, across a gridded terrain surface. Landscape
    models have a number of commonalities, such as operating on a
    grid of points and routing material across the grid. Scientists
    who want to use a landscape model often build their own unique
    model from the ground up, re-coding the basic building blocks
    of their landscape model rather than taking advantage of codes
    that have already been written.
  doc_url: https://landlab.readthedocs.io
  dev_url: https://github.com/landlab/landlab

extra:
  recipe-maintainers:
    - mcflugen
    - lsetiawan
    - ocefpaf
    - kbarnhart
    - nathanlyons
