{% set version = "1.10.1" %}

package:
  name: landlab
  version: {{ version }}

source:
  url: https://github.com/landlab/landlab/archive/v{{ version }}.tar.gz
  sha256: 9a4baedb69e452bfe95ebccec2aaed47d2e91b6e8245cbea185aaf8dbb8248f6

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler("c") }}
  host:
    - python
    - pip
    - cython
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - bmipy
    - matplotlib-base
    - netcdf4
    - pyshp
    - pyyaml
    - scipy
    - six
    - statsmodels
    - xarray

test:
  requires:
    - pytest
    - pytest-datadir
  imports:
    - landlab
  commands:
    - export MPLBACKEND=Agg  # [not win]
    # skipping the tests b/c they have some flaky repr comparisons
    # - pytest --pyargs landlab --doctest-modules -o doctest_optionflags="NORMALIZE_WHITESPACE IGNORE_EXCEPTION_DETAIL ALLOW_UNICODE"

about:
  home: http://landlab.github.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A python toolkit for modeling earth surface processes
  description: |
    Landlab creates an environment in which scientists can build
    a numerical landscape model without having to code all of the
    individual components. Landscape models compute flows of mass,
    such as water, sediment, glacial ice, volcanic material, or
    landslide debris, across a gridded terrain surface. Landscape
    models have a number of commonalities, such as operating on a
    grid of points and routing material across the grid. Scientists
    who want to use a landscape model often build their own unique
    model from the ground up, re-coding the basic building blocks
    of their landscape model rather than taking advantage of codes
    that have already been written.
  doc_url: https://landlab.readthedocs.io
  dev_url: https://github.com/landlab/landlab

extra:
  recipe-maintainers:
    - mcflugen
    - lsetiawan
    - ocefpaf
    - kbarnhart
