travis:
  secure:
    BINSTAR_TOKEN: FdBujE0t7ukiS4/vjh6onqhPiiR9lDSPGEKGl3CTDHKeKXuO6Q9wDVy7zBTmVR0viVseu9wa0xudbJHyOgCd67amTSpYGcShoxOkW0/69nxYBzCCNpjS99IcZEPWsZWO/2FBSr4GCKfDIS8tvAebO6Qk9zRdExO5cBncPmGMKh97LW9/BOitIR4rMjA/Db0pVn6H+HbVz7NdsJ7fb8BDKtlq9lPOXhNfPn7ZoaOQ9Kjs2o2yFNIRo0Tc/iU9fPs4LLbWEmAaiB6r1svk6VeTJeqX2HZ20ZoDyAWLKkkGbWvh6w9YraGbPCRu8srXM3+6J+bsbsStyVp+10JZuCH4WHBWQysdh+aejMKmXiwZP1M68aJVpdu0ZwMLM50HuRmvEeChgqJmHdTmuPdUmxhLM4NTMzDGTjM/Ua6wibc6WyzzkOfDVkXKY6nWj/W6JStNyYiFxqj8LXWQL3Ro+j0jNgyKuxNW4Jfzm4DaGUbbLibiMMKHu2yvjrm+qqC9nk/lQz28rwhl8Fq9P7hQNyoDMTxW1I2YZdq+1eUVbvO+FM+AyH6Yaev7Q3IgxAe77UuH6QXsDpJxiL5AOINxIpEmRocJb93hw8qd0Z7Y0KxVeCggiHil2zkbyMuyMZ9HOUBOqHOHj6XcWa+568Z7fzWYlWc5Vtdsv6Y1hcikBONjY9U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
